import React, { createContext, useContext, useState } from "react";
import { useAuthentication } from "./Hook/useAuthentication";
import useEmployees from "./Hook/useEmployees";
import { useTeacher } from "./Hook/useTeachers";
import { useClass } from "./Hook/useClass";
import { useStudent } from "./Hook/useStudent";
import { useHome } from "./Hook/useHome";
import { useAccounting } from "./Hook/useAccounting";
import { useSearch } from "./Hook/useSearch";
import { useGrand_Total_Income } from "./Hook/useGrand_Total_Income";
import { useListStudentAttendance } from "./Hook/useListStudentAtt";
import { useDashboardAccounting } from "./Hook/useDashboardAccounting";
import { useExpenses } from "./Hook/useExpenses";
import { useDataDashboard } from "./Hook/useDataDashboard";
import { useDetailStudent } from "./Hook/useDetailStudent";
import { useReport } from "./Hook/useReport";
import { useNotification } from "./Hook/useNotification";
const controlDataContext = createContext();
const useDataContext = () => useContext(controlDataContext);
function Context({ children }) {
  const [loading, setLoading] = useState(true);
  const [localLoading, setLocalLoading] = useState(true);
  const [searchLoading, setSearchLoading] = useState(true);
  const [searchStudentPayment, setSearchStudentPayment] = useState("");
  const [showHidden, setShowHidden] = useState(false);
  const [notification, setNotification] = useState(false);
  const [newStudent, setNewStudent] = useState(false); //for add new student and fetch employee
  const [dataStudent, setDataStudent] = useState([]);
  const [dataStudentSearch, setDataStudentSearch] = useState([]);
  const [totalPaidUnpaid, setTotalPaidUnpaid] = useState([]);
  const [topRankStudent, setTopRankStudent] = useState([]);
  const [book_id, setBook_id] = useState(null);

  const [loadLink, setLoadLink] = useState(null); //use for load date when change location page via link
  const [pages, setPages] = useState({
    employee: { page: 1, limit: 10 },
    teacher: { page: 1, limit: 10 },
    student: { page: 1, limit: 10 },
    accounting: { page: 1, limit: 10 },
    report: { page: 1, limit: 10 },
    expenses: { page: 1, limit: 10 },
    attendance: { page: 1, limit: 10 },
    searchStudent: { page: 1, limit: 10 },
    searchByDate: { page: 1, limit: 10 },
    reporting: { page: 1, limit: 10 },
    receiver: { page: 1, limit: 10 },
  });
  const updatePage = (module, newPage) => {
    setPages((prev) => ({
      ...prev,
      [module]: {
        ...prev[module],
        page: newPage,
      },
    }));
  };
  const [formStudent, setFormStudent] = useState({
    class_id: "",
    employee_id: "",
    book_id: "",
    id_card: "",
    first_name: "",
    last_name: "",
    gender: "",
    dob: "",
    telephone: "",
    address: "",
    description: "",
    createdAt: "",
    shift: "",
    start_time: "",
    end_time: "",
  });
  const url = "my-backend-production-b2d1.up.railway.app";
  const {
    loginFalse,
    setLoginFalse,
    handleChange,
    handleLogin,
    redirect,
    auth,
    user,
    logout,
  } = useAuthentication({ url, loading, setLoading });

  const {
    handleGetAllTeacher,
    teacher,
    setTeacher,
    TeacherDetailModal,
    handleChangeTeacher,
    detaiModal,
    setDetailModal,
    teacherBook,
    handleChangeTeacherBook,
    showFormTeacherbook,
    setShowFormTeacherBook,
    getTeacherBook,
    storeTeacherBook,
    handleTeacherBook,
    loadingTeacher,
    showTeacherBook,
    setShowTeacherBook,
  } = useTeacher({
    url,
  });
  const {
    listEmployee,
    employees,
    setEmployees,
    error,
    handleChangeEmployee,
    handleCrateEmployee,
    formEmployees,
    setFormEmployees,
    handleUpdateEmployee,
    handleDeleteEmployee,
    views,
    setViews,
    OneEmp,
    empPaginate,
    loadingEmployee,
    initialEmployee,
  } = useEmployees({
    url,
    handleGetAllTeacher,
    auth,
    pages,
    loadLink,
    newStudent,
  });
  const { formClass, setFormClass, className } = useClass({
    url,
    setLoading,
    auth,
  });
  const {
    amount,
    chartStudentPaymentAmount,
    setchartStudentPaymentAmount,
    summaryTotal_active_student,
    dataStudentActiveDeactive,
    setDataStudentActiveDeactive,
    dataBook,
    setDataBook,
    chart_attendance_student,
    total_expenses,
    storeChartExpenses,
    loadingDashboard,
  } = useDataDashboard({
    setTotalPaidUnpaid,
    url,
    auth,
  });
  const {
    showFormPayment,
    setShowFormPayment,
    handleChangePaymentStudent,
    insertPaymentStudent,
    payment,
    paidStudentType,
    setType,
    type,
    fetchStudentPayment,
    loadingAccounting,
    setpaidStudentType,
    searchPaidUnpaid,
    setSearchPaidUnpaid,
    searchStudentPaidUnpaid,
    paginate,
    setPaginate,
    setPayment,
    updatePaymentStudent,
    changeEdit,
    setChangeEdit,
  } = useAccounting({
    url,
    setNewStudent,
    setFormStudent,
    searchStudentPayment,
    setSearchStudentPayment,
    pages,
    loadLink,
  });
  const {
    handleChangeStudent,

    handleInsertStudent,
    listBook,

    showAttendance,
    setShowAttendance,
    handleAttendance,
    listStudentAtt,
    attendancePiaginate,
    formAttendance,
    handleChangeStudentAttendance,
    handleChangeStudentPoint,
    handleInsertStudentPoint,
    formStudentPoint,
    showPoint,
    setShowPoint,
    listStudentPoint,
    teacher_ID,
    setTeacher_ID,
    handleDeleteStudent,
    handleReactiveStudent,
    studentPaginate,
    total_students_teacher,
    searchStudentAt,
    setSearchStudentAt,
    handleSearchStudents,
    active,
    setActive,
    updateStudentInfomationf,
  } = useStudent({
    url,
    setLocalLoading,
    auth,
    setShowFormPayment,
    teacher,
    setDataStudent,
    fetchStudentPayment,
    paidStudentType,
    dataStudent,
    dataStudentSearch,
    setDataStudentSearch,
    book_id,
    setBook_id,
    pages,
    setPages,
    formStudent,
    setFormStudent,
    setDataStudentActiveDeactive,
    setDataBook,
    setTopRankStudent,
    loadLink,
  });
  const { chartData, chartsLevel } = useHome({
    dataStudent,
    auth,
    dataStudentActiveDeactive,
    dataBook,
  });

  const {
    searchStudent,
    setSearchStudent,
    handleSearchStudent,
    handleSearchStudentPayment,

    startDate,
    setStartDate,
    endDate,
    setEndDate,
    handleFilterByDate,
    studentSearch,
  } = useSearch({
    auth,
    url,
    setDataStudentSearch,
    setLoading,
    setchartStudentPaymentAmount,
    pages,
    searchLoading,
    setSearchLoading,
    searchStudentPayment,
    setpaidStudentType,
    setPaginate,
  });
  const {
    totalIncome,
    setTotalIncome,
    totalPaid,
    setTottalPaid,
    totalUnpaid,
    setTotalUnpaid,
    totalOverdue,
    thisMonthIncome,
    lastMonthIncome,
    percentageChange,
    monthlyChartData,
  } = useGrand_Total_Income({
    auth,
    url,
    chartStudentPaymentAmount,
  });
  const { chartDataAtt } = useListStudentAttendance({
    chart_attendance_student,
  });

  const {
    showCategoryForm,
    setShowCategoryForm,
    showExpensesForm,
    setShowExpensesForm,
    storeCategories,
    handleChangeCategories,
    handleChangeExpenses,
    insertCategories,
    insertExpenses,
    formCategories,
    formExpenses,
    storeExpenses,
    expensePaginate,
    loadingExpenses,
    typeExpense,
  } = useExpenses({ url, auth, pages, loadLink });
  const {
    chartTotalMonthlyYearly,
    lastMonthTotalAmount,
    thisMonthTotalAmount,
    percentAmountRegister,
    lastMonthTotalAmount_transport_fee,
    thisMonthTotalAmount_transport_fee,
    percentAmountRegister_transport_fee,
    lastMonthTotalAmount_register_transport_fee,
    thisMonthTotalAmount_register_transport_fee,
    percentAmountRegister_register_transport_fee,

    lastMonthExpesesAmount,
    thisMonthExpensesAmount,
    percentExpensesAmount,
  } = useDashboardAccounting({ chartStudentPaymentAmount, storeChartExpenses });
  const { detaiStudentlLoading, infoDetailStudent, getDetailStudent } =
    useDetailStudent({ url });
  const {
    typeNameReport,
    setTypeNameReport,
    storeReportData,
    loadingReport,
    downloadExcel,
    downloadPDF,
    paginateReport,
    startDateRP,
    setStartDateRP,
    endDateRP,
    setEndDateRP,
    getReporting,
  } = useReport({ url, auth, pages, book_id });
  const {
    readNotification,
    loadingNotification,
    sendNotification,
    handleChangeNotification,
    formNotification,
    storeReceiver,
    searchReceiver,
    setSearchReceiver,
    markReadMessage,
    alertNotification,
    setAlertNotification,
  } = useNotification({
    url,
    setNotification,
    pages,
    auth,
  });
  return (
    <controlDataContext.Provider
      value={{
        notification,
        loadingNotification,
        setNotification,
        sendNotification,
        handleChangeNotification,
        alertNotification,
        setAlertNotification,
        readNotification,
        markReadMessage,
        formNotification,
        storeReceiver,
        searchReceiver,
        setSearchReceiver,
        updatePage,
        pages,
        setPages,
        loadLink,
        setLoadLink,
        topRankStudent,
        setTopRankStudent,
        book_id,
        setBook_id,
        dataStudentActiveDeactive,
        setDataStudentActiveDeactive,
        logout,
        dataStudent,
        setDataStudent,
        showHidden,
        setShowHidden,
        loginFalse,
        setLoginFalse,
        loading,
        setLoading,
        localLoading,
        setLocalLoading,
        handleChange,
        handleLogin,
        redirect,
        auth,
        user,

        paginate,
        setPaginate,
        listEmployee,
        employees,
        setEmployees,
        error,
        handleChangeEmployee,
        handleCrateEmployee,
        handleUpdateEmployee,
        formEmployees,
        setFormEmployees,
        handleDeleteEmployee,
        views,
        setViews,
        OneEmp,
        empPaginate,
        handleGetAllTeacher,
        teacher,
        setTeacher,
        TeacherDetailModal,
        handleChangeTeacher,
        detaiModal,
        setDetailModal,
        formClass,
        setFormClass,
        className,
        handleChangeStudent,
        formStudent,
        setFormStudent,
        setpaidStudentType,
        handleInsertStudent,
        listBook,
        newStudent,
        setNewStudent,
        chartData,
        chartsLevel,
        showFormPayment,
        setShowFormPayment,
        handleChangePaymentStudent,
        insertPaymentStudent,
        payment,
        setPayment,
        updatePaymentStudent,
        changeEdit,
        setChangeEdit,
        fetchStudentPayment,
        chartStudentPaymentAmount,
        paidStudentType,
        setType,
        type,
        showAttendance,
        setShowAttendance,
        handleAttendance,
        listStudentAtt,
        attendancePiaginate,
        formAttendance,
        handleChangeStudentAttendance,
        handleChangeStudentPoint,
        handleInsertStudentPoint,
        formStudentPoint,
        showPoint,
        setShowPoint,
        listStudentPoint,
        teacher_ID,
        setTeacher_ID,
        handleDeleteStudent,
        handleReactiveStudent,

        setchartStudentPaymentAmount,
        teacherBook,
        handleChangeTeacherBook,
        loadingDashboard,
        showFormTeacherbook,
        setShowFormTeacherBook,
        getTeacherBook,
        loadingExpenses,
        typeExpense,
        storeTeacherBook,
        handleTeacherBook,
        searchStudent,
        setSearchStudent,
        loadingAccounting,
        handleSearchStudent,
        handleSearchStudentPayment,
        searchStudentPayment,
        setSearchStudentPayment,
        startDate,
        setStartDate,
        studentSearch,
        searchLoading,
        setSearchLoading,
        endDate,
        setEndDate,
        handleFilterByDate,
        totalIncome,
        setTotalIncome,
        totalPaid,
        setTottalPaid,
        totalUnpaid,
        loadingEmployee,
        initialEmployee,
        setTotalUnpaid,
        totalOverdue,
        thisMonthIncome,
        lastMonthIncome,
        percentageChange,
        monthlyChartData,
        chartDataAtt,
        showCategoryForm,
        setShowCategoryForm,
        showExpensesForm,
        setShowExpensesForm,
        storeCategories,
        handleChangeCategories,
        handleChangeExpenses,
        insertCategories,
        insertExpenses,
        formCategories,
        formExpenses,
        storeExpenses,
        expensePaginate,
        summaryTotal_active_student,
        studentPaginate,
        amount,
        totalPaidUnpaid,
        chartTotalMonthlyYearly,
        lastMonthTotalAmount,
        thisMonthTotalAmount,
        percentAmountRegister,
        lastMonthTotalAmount_transport_fee,
        thisMonthTotalAmount_transport_fee,
        percentAmountRegister_transport_fee,
        lastMonthExpesesAmount,
        thisMonthExpensesAmount,
        percentExpensesAmount,
        lastMonthTotalAmount_register_transport_fee,
        thisMonthTotalAmount_register_transport_fee,
        percentAmountRegister_register_transport_fee,
        total_expenses,
        total_students_teacher,
        detaiStudentlLoading,
        infoDetailStudent,
        getDetailStudent,
        searchPaidUnpaid,
        setSearchPaidUnpaid,
        searchStudentPaidUnpaid,
        searchStudentAt,
        setSearchStudentAt,
        handleSearchStudents,
        active,
        setActive,
        updateStudentInfomation,
        typeNameReport,
        setTypeNameReport,
        storeReportData,
        loadingReport,
        downloadExcel,
        downloadPDF,
        paginateReport,
        startDateRP,
        setStartDateRP,
        endDateRP,
        setEndDateRP,
        getReporting,
        loadingTeacher,
        showTeacherBook,
        setShowTeacherBook,
      }}
    >
      {children}
    </controlDataContext.Provider>
  );
}
export { useDataContext };
export default Context;
